### ISSUE TITLE
Fairly certain I have the incorrect primes

### ISSUE THREAD

**Issue by nessamurmur** [nessamurmur/caesar-ciphers#3]
Valid primes should be _relatively prime_ to 127. Not just prime numbers below 127.

https://github.com/niftyn8/caesar-ciphers/blob/master/lib/caesar.ex#L36-L42

**Comment by nessamurmur** [comment]
I _think_ I actually have correct values...

``` elixir
iex(2)> Enum.filter( Caesar.valid_primes, fn(num) -> rem(127,  num) == 0 end )      
[]
```

Going to see if I can find someone to confirm...

**Comment by nessamurmur** [comment]
Realized this is obvious because 127 is a prime. Woops.

**Comment by lasandell** [comment]
I was about to leave a comment to that effect because the requirement had me very confused. :)

**Comment by nessamurmur** [comment]
@lasandell it would matter if I was only working with the 26 letters of the alphabet in lower or upper case since 25 is not a prime. Was thinking about that use case and not thinking about the fact that 127 is a prime.

**Comment by nessamurmur** [comment]
@lasandell in other words, I'm not a mathematician but I'm trying to learn.

**Comment by lasandell** [comment]
Me either, I had to look up what "relatively prime" meant.
